on:
  workflow_call:
    outputs:
      claude_app_installed:
        type: boolean

jobs:
  check_install:
    runs-on: ubuntu-latest
    outputs:
      claude_app_installed: ${{ steps.check.outputs.installed == 'true' }}
    steps:
      - name: Check Claude GitHub App installed
        id: check
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            try {
              await github.rest.apps.getRepoInstallation({
                owner: context.repo.owner,
                repo: context.repo.repo
              });
              return { installed: 'true' };
            } catch (err) {
              if (err.status === 404) return { installed: 'false' };
              throw err;
            }
